# Generated by Django 4.2.4 on 2023-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='brand_featured_products', to='product.product', verbose_name='Featured Products'),
        ),
    ]
