# Generated by Django 3.1.7 on 2021-04-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=100)),
                ('adminemail', models.CharField(max_length=100)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adminuser',
            },
        ),
        migrations.CreateModel(
            name='Subcriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subemail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subscriber',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.DeleteModel(
            name='shoes',
        ),
    ]
