# Generated by Django 3.1.7 on 2021-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210420_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
