# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables from .env file
ENV POSTGRES_DB=${POSTGRES_DB} \
    POSTGRES_USER=${POSTGRES_USER} \
    POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    POSTGRES_PORT=${POSTGRES_PORT}
